title: The Piganelli Lab
description: Redox immunology, T cell metabolism, and type 1 diabetes research at Indiana University School of Medicine.

baseurl: "/PiganelliLaboratory"
url: "https://mproffer-17.github.io"
