title: The Piganelli Lab
description: Redox immunology, T cell metabolism, and type 1 diabetes research at Indiana University School of Medicine.
theme: jekyll-theme-minimal

baseurl: "/mproffer/PiganelliLaboratory.github.io"
url: "https://pages.github.iu.edu"
